---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[depot::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
#    driver_config:
#      network:
#        - [ "private_network", {ip: "192.168.96.31"} ]
